version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://iamsrte:12345678@localhost:5432/safeguard
    ports:
      - "8000:8000"

  db:
      image: postgres:15-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5433
      environment:
        - POSTGRES_USER=iamsrte
        - POSTGRES_PASSWORD=12345678
        - POSTGRES_DB=safeguard

volumes:
      postgres_data: